export const categories = [
  {
    id: 1,
    name: "Pizza",
    image: require("../../assets/categories/icons8-pizza-96.png"),
  },
  {
    id: 2,
    name: "Burguer",
    image: require("../../assets/categories/icons8-hamburger-96.png"),
  },
  {
    id: 3,
    name: "Italian",
    image: require("../../assets/categories/icons8-spaghetti-96.png"),
  },
  {
    id: 4,
    name: "Chinese",
    image: require("../../assets/categories/icons8-takeout-box-96.png"),
  },
  {
    id: 5,
    name: "Noodles",
    image: require("../../assets/categories/icons8-takeout-box-96.png"),
  },
  {
    id: 6,
    name: "Sweets",
    image: require("../../assets/categories/icons8-cupcake-emoji-96.png"),
  },
];

export const featured = {
  id: 1,
  title: "hot and Spicy",
  description: "soft and tender fried chicken",
  restaurants: [
    {
      id: 1,
      name: "Kpricho Lanches - Leste SJC",
      image: require("../../assets/images/restaurants/pizzatesteimage.jpg"),
      description: "Lanches rápidos e saborosos. Venha experimentar!",
      lng: -45.852608404258845,
      lat: -23.180430447715885,
      address: "Av. Pres. Juscelino Kubitschek, 7858\nVila Tatetuba, São José dos Campos - SP,\n12220-000",
      stars: 5,
      reviews: "4.4k",
      category: "Hamburgueria",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../../assets/images/restaurants/pizzatesteimage.jpg"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../../assets/images/restaurants/pizzatesteimage.jpg"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../../assets/images/restaurants/pizzatesteimage.jpg"),
        },
      ],
    },
    {
      id: 2,
      name: "papa johns",
      image: require("../../assets/images/restaurants/pizzatesteimage.jpg"),
      description: "hot and Spicy pizzas",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../../assets/images/dishes/pizzadlc.jpeg"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../../assets/images/dishes/pizzadlc.jpeg"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../../assets/images/dishes/pizzadlc.jpeg"),
        },
      ],
    },
    {
      id: 3,
      name: "papa johns",
      image: require("../../assets/images/dishes/pizzadlc.jpeg"),
      description: "hot and Spicy pizzas",
      lng: 38.2145602,
      lat: -85.5324269,
      address: "434 second street",
      stars: 4,
      reviews: "4.4k",
      category: "Fast Food",
      dishes: [
        {
          id: 1,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../../assets/images/dishes/pizzadlc.jpeg"),
        },
        {
          id: 2,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../../assets/images/dishes/pizzadlc.jpeg"),
        },
        {
          id: 3,
          name: "pizza",
          description: "cheezy garlic pizza",
          price: 10,
          image: require("../../assets/images/dishes/pizzadlc.jpeg"),
        },
      ],
    },
  ],
};
